services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: mysql-container
    expose:
      - “3306”
    env_file:
      - .env
    volumes:
      - ./db/conf:/etc/mysql/conf.d
      - ./db/init:/docker-entrypoint-initdb.d
