name: Frontend Workflow
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  call-frontend-workflow-pr:
    if: github.event_name == 'pull_request'
    uses: ./frontend/.github/workflows/frontend-action.yml@${{ github.head_ref }}

  call-frontend-workflow-push:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: ./frontend/.github/workflows/frontend-action.yml@${{ github.ref_name }}
