name: Frontend Workflow
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  call-frontend-workflow:
    uses: ./frontend/.github/workflows/frontend-action.yml@${{ github.head_ref || github.ref_name }}
